### ISSUE TITLE
[CSSU Lounge] Improve wayfinding

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#3]
<strong>This issue was created automatically as a suggestion was submitted in the Google Form.</strong> 
 <strong>Submitted By: </strong>John Doe

I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds. I need to find the Northrop Frye McDonalds.

**Comment by JasonBarahan** [comment]
![image](https://github.com/cssu/suggestions/assets/122300705/31ab02da-659d-485c-bc86-b6e3dad911c8)
There it is
