### ISSUE TITLE
[ ] gyatt

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#53]
<i>This issue was created automatically as a suggestion was submitted in the Google Form.</i> 
 <strong>Submitted By: </strong> 

 <strong>Details: </strong>gyatt ![image](https://github.com/cssu/suggestions/assets/170150070/d9468167-0f4e-44b2-86da-b2b094a1ea7d)

**Comment by sonofthomp** [comment]
Quality stuff 👍
