### ISSUE TITLE
[CSSU Lounge] Hey its me TheCSSUBurglar

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#6]
<i>This issue was created automatically as a suggestion was submitted in the Google Form.</i> 

 <strong>Submitted By: </strong>The CSSU Burglar
 <strong>Details:</strong>I think the CSSU needs to be more nice to burglars. I went in last time in 2011-ish and got escorted out by Campus Safety. I just wanted to grab a cola but the international student tuition fees got me and I got stressed by problem set 4 in mat137 so please let me do this thing ONCE

**Comment by JasonBarahan** [comment]
This you? https://www.youtube.com/watch?v=t4E-DpgfGMo

(Spoiler: this was a test issue)
