### ISSUE TITLE
[Information] Post this in the lounge please?

### ISSUE THREAD

**Issue by cssutoronto** [cssu/suggestions#7]
<i>This issue was created automatically as a suggestion was submitted in the Google Form.</i> 
 <strong>Submitted By: </strong>Meric Gertler trust me bro

 <strong>Details: </strong>n Internet culture, shitposting or trashposting is the act of using an online forum or social media page to post content that is of "aggressively, ironically, and trollishly poor quality".[1] Shitposts are generally intentionally designed to derail discussions or cause the biggest reaction with the least effort. It may even sometimes be orchestrated as part of a co-ordinated flame war to render a website unusable by its regular visitors.[2]

Definition and usages
Shitposting is a modern form of online provocation. The term itself appeared around the mid-2000s on image boards such as 4chan. Writing for Polygon, Sam Greszes compared shitposting to Dadaism's "confusing, context-free pieces that, specifically because they were so absurd, were seen as revolutionary works both artistically and politically". Greszes writes that the goal of shitposting is "to make an audience so confused at the lack of content that they laugh or smile".[3]

Professor Greg Barton, an expert on terrorism at Deakin University, said that racist shitposting is common across the internet and is a way for people to connect and gain attention. He said, "The thing about social media is that it's social. You want some feedback, you want people to like your stuff whether it's Instagram or Facebook. Shitposting is all about getting your profile up, getting a response and the more ironic and funny you can be the more you get."[4][5]

In modern politics
The political uses of shitposting came to prominence during the 2016 United States presidential election. In May of that year, The Daily Dot wrote that a shitpost is "a deliberate provocation designed for maximum impact with minimum effort".[6]

In September 2016 the pro-Trump group Nimble America received widespread media attention.[7][8][9] The Daily Beast described the group as "dedicated to 'shitposting' and circulating internet memes maligning Hillary Clinton".[7]

In September 2016, The Independent wrote that shitposting is an apolitical "tool that can be put to a variety of effects".[10] But posts such as these appeared long before the 2016 US presidential election. Engineering & Technology magazine wrote that "shitposting, whether from the left or right, is perilously close to delivering an online metastasis of Orwell's Two-minute Hate [sic]".[11]

In November 2016, Esquire magazine wrote, "internet mockery is emerging as a legitimate political technique: shitposting. Maybe the 2020 election will be all shitposting."[12]

In March 2018, talking about Facebook group New Urbanist Shitposting or New Urbanist Memes for Transit-Oriented Teens, Chicago magazine defined it as "posts that are meant to be awkward and irrelevant, aggravating and distracting social media communities from discussing their topic at hand".[13][14]

The Financial Times defined shitposting as "posting ostentatiously inane and contextless content to an online forum or social network with the effect of derailing discussion". It gave the example of British former Liberal Democrat leader Jo Swinson being forced to deny she had killed squirrels for fun after online trolls made up a story about her having done so.[15][16]

**Comment by JasonBarahan** [comment]
I don't think this would be a good idea.
